name: GiantTrees
version: "${project.version}"
api-version: "1.21"
author: Ryan Michela
main: com.ryanmichela.trees.TreePlugin
description: Grows enormous trees.
load: STARTUP

commands:
   tree-edit:
      description: Opens the giant tree editor. Can only be called from the server console.
      usage: "Usage: tree-edit species"
   tree-create:
      description: Creates a giant tree.
      aliases: gt
      permission: gianttrees.create
      usage: "Usage: /<command> [species]"

permissions:
   gianttrees.create:
      description: Allows the creation of a giant tree using the tree-create command.
      default: op
   gianttrees.grow:
      description: Allows a player to grow a giant tree by fertilizing a grid of saplings.
      default: true
